<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LotSizingDataModel.Core\LotSizingDataModel.Core.csproj" />
    <ProjectReference Include="..\LotSizingDataModel.Solution\LotSizingDataModel.Solution.csproj" />
  </ItemGroup>

</Project>
