<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseAppHost>false</UseAppHost>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LotSizingDataModel.Checker\LotSizingDataModel.Checker.csproj" />
    <ProjectReference Include="..\LotSizingDataModel.Instance\LotSizingDataModel.Instance.csproj" />
    <ProjectReference Include="..\LotSizingDataModel.Solver\LotSizingDataModel.Solver.csproj" />
    <ProjectReference Include="..\LotSizingDataModel.Solver.Cplex\LotSizingDataModel.Solver.Cplex.csproj" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\LotSizingDataModel.Solver.Gurobi\LotSizingDataModel.Solver.Gurobi.csproj" />
    <ProjectReference Include="..\LotSizingDataModel.Solver.Xpress\LotSizingDataModel.Solver.Xpress.csproj" />
    <ProjectReference Include="..\LotSizingDataModel.Solver.CoinOrCbc\LotSizingDataModel.Solver.CoinOrCbc.csproj" />
  </ItemGroup>
</Project>
