<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LotSizingDataModel.Checker\LotSizingDataModel.Checker.csproj" />
    <ProjectReference Include="..\LotSizingDataModel.Instance\LotSizingDataModel.Instance.csproj" />
  </ItemGroup>

</Project>
